### ISSUE TITLE
Check {hierfstat} and use some of its functions?

### ISSUE THREAD

**Issue by DWFbio** [courtiol/R4Genetics#10]
**Hierfstat** works for pairwise Fst, but requires another data transformation, and does not calculate confidence or P-value

```r
library(adegenet)
library(hierfstat)
myData <- read.genepop(file = "data/microbov_small.gen", ncode = 3, quiet = TRUE)
myData_hierf <- genind2hierfstat(myData, pop = NULL)
pairwise.WCfst(myData_hierf, diploid = TRUE)
```

**Comment by courtiol** [comment]
It does provide CI:
```r
boot.ppfst(myData_hierf)
```

and we should probably use it; see #4

**Comment by courtiol** [comment]
We should also use `hierfstat::basic.stats()` to do most heterozygosity stuff.
See https://github.com/thibautjombart/adegenet/issues/301

**Comment by jgx65** [comment]
see https://github.com/thibautjombart/adegenet/issues/301#issuecomment-783628574

**Comment by courtiol** [comment]
Note that we also have pegas::H(), see e.g. https://github.com/emmanuelparadis/pegas/pull/52#event-4369033665
